[server]
host = "0.0.0.0"
port = 8000

[resources]
data_path = "./data" # Path relative to web_server/ or absolute

# [tls] # For future use
# enabled = false
# keyfile = "/path/to/key.pem"
# certfile = "/path/to/cert.pem"
